import parseSubtitle from "../utils/SubtitleParser.js";

const subtitles_1 = [
    "[MUSIC PLAYING ON RADIO]",
    "[SEAGULLS DISTANTLY SCREECHING]",
    "[OCEAN WAVES]",
    "[MUSIC PLAYING ON RADIO]",
    "♪♪♪",
    "♪ NOW HE’S ♪",
    "♪ THINKIN’ BOUT ME ♪",
    "♪ EVERY NIGHT, OH ♪",
    "♪ IS IT THAT SWEET? I GUESS SO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ MOVE IT UP DOWN ♪",
    "♪ LEFT RIGHT, OH ♪",
    "♪ SWITCH IT UP LIKE NINTENDO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ I CAN’T RELATE ♪",
    "♪ TO DESPERATION ♪",
    "♪ MY ‘GIVE A FUCKS’ ♪",
    "♪ ARE ON VACATION ♪",
    "♪ AND I GOT THIS ONE BOY ♪",
    "♪ AND HE WON’T STOP CALLING ♪",
    "♪ WHEN THEY ACT THIS WAY ♪",
    "♪ I KNOW I GOT EM’ ♪",
    "♪ (HM) TOO BAD YOUR EX DON’T DO\nIT FOR YA ♪",
    "♪ (HM) WALKED IN AND DREAM CAME\nTRUED IT FOR YA ♪",
    "♪ (HM) SOFT SKIN AND I PERFUMED\nIT FOR YA ♪",
    "♪♪♪",
    "♪ (YES) I KNOW I MOUNTAIN DEW IT\nFOR YA ♪",
    "♪ (YES) THAT MORNING COFFEE\nBREWED IT FOR YA ♪",
    "♪ (YES) ONE TOUCH AND I BRAND\nNEWED IT FOR YA ♪",
    "♪ [VOCALIZING] ♪",
    "♪ NOW HE’S ♪",
    "♪ THINKIN’ BOUT ME\nEVERY NIGHT, OH ♪",
    "♪ EVERY NIGHT, OH ♪",
    "♪ IS IT THAT SWEET?\nI GUESS SO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ MOVE IT UP DOWN ♪",
    "♪ LEFT RIGHT, OH ♪",
    "♪ SWITCH IT UP LIKE NINTENDO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ (HOLY SHIT) ♪",
    "♪♪♪",
    "♪ IS IT THAT SWEET?\nI GUESS SO ♪",
    "♪ I’M WORKING LATE (LATE) ♪",
    "♪ CAUSE I’M A SINGER (UH) ♪",
    "♪ OH HE LOOKS SO CUTE (CUTE) ♪",
    "♪ WRAPPED AROUND MY FINGER\n(YEAH) ♪",
    "♪ MY TWISTED HUMOR (HUMOR) ♪",
    "♪ MAKE HIM LAUGH SO OFTEN ♪",
    "♪ MY HONEY BEE (BEE) ♪",
    "♪ COME AND GET THIS POLLEN ♪",
    "♪ (HM) TOO BAD YOUR EX DON’T DO\nIT FOR YA ♪",
    "♪ (HM) WALKED IN AND DREAM CAME\nTRUED IT FOR YA ♪",
    "♪ (HM) SOFT SKIN AND I PERFUMED\nIT FOR YA ♪",
    "♪♪♪",
    "♪ (YES) I KNOW I MOUNTAIN\nDEW IT FOR YA ♪",
    "♪ (YES) THAT MORNING COFFEE\nBREWED IT FOR YA ♪",
    "♪ (YES) ONE TOUCH AND I BRAND\nNEWED IT FOR YA ♪",
    "♪ (STUPID) ♪",
    "♪♪♪",
    "♪ NOW HE’S ♪",
    "♪ THINKIN’ BOUT ME ♪",
    "♪ EVERY NIGHT, OH ♪",
    "♪ IS IT THAT SWEET?\nI GUESS SO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ MOVE IT UP DOWN ♪",
    "♪ LEFT RIGHT, OH ♪",
    "♪ SWITCH IT UP LIKE NINTENDO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ HE’S THINKIN’ BOUT ME ♪",
    "♪ EVERY NIGHT, OH ♪",
    "♪ IS IT THAT SWEET?\nI GUESS SO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪ MOVE IT UP DOWN ♪",
    "♪ LEFT RIGHT, OH ♪",
    "♪ SWITCH IT UP LIKE NINTENDO ♪",
    "♪ SAY YOU CAN’T SLEEP ♪",
    "♪ BABY I KNOW ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "♪♪♪",
    "♪ IS IT THAT SWEET?\nI GUESS SO ♪",
    "♪♪♪",
    "♪ VOCALIZING ♪",
    "♪ THAT’S THAT ME ESPRESSO ♪",
    "[POLICE RADIO CHATTER]",
    "[ENGINE TURNING OVER]",
    "[POLICE RADIO CHATTER]",
    "[ENGINE TURNING OVER]",
    "[POLICE RADIO CHATTER]",
    "[MUSIC PLAYING ON RADIO]"
];

const subtitles_2 = [
    "Know I&#39;ve done wrong,\nleft your heart torn",
    "Is that what devils do?",
    "Took you so low, where only fools go",
    "I shook the angel in you",
    "Now I&#39;m rising from the ground",
    "Rising up to you",
    "Filled with all the strength I found",
    "There&#39;s nothing I can&#39;t do",
    "I need to know now, know now",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again?",
    "Can you love me again?",
    "It&#39;s unforgivable",
    "I stole and burnt your soul",
    "Is that what demons do?",
    "They rule the worst of me",
    "Destroy everything",
    "They bring down angels like you",
    "Now I&#39;m rising from the ground",
    "Rising up to you",
    "Filled with all the strength I found",
    "There&#39;s nothing I can&#39;t do",
    "I need to know now, know now\n&lt;br&gt;",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again?",
    "Can you love me again?",
    "Oh, I told you once again",
    "I can&#39;t do this again,\ndo this again, oh",
    "I told you once again",
    "I can&#39;t do this again,\ndo this again, oh no",
    "I need to know now, know now",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again?",
    "I need to know now, know now",
    "Can you love me again (Oh, oh)",
    "Can you love me again?"
];

const subtitles_3 = [
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars,\nwe&#39;ll be counting stars ♪",
    "♪ Yeah, we&#39;ll be counting stars ♪",
    "(&quot;Counting Stars&quot;)",
    "(upbeat rock music)",
    "♪ I see this life, like a swinging vine ♪",
    "♪ Swing my heart across the line ♪",
    "♪ And in my face is flashing signs ♪",
    "♪ Seek it out and ye shall find ♪",
    "♪ Old, but I&#39;m not that old ♪",
    "♪ Young, but I&#39;m not that bold ♪",
    "♪ And I don&#39;t think the world is sold ♪",
    "♪ On just doing what we&#39;re told ♪",
    "♪ I feel something so right ♪",
    "♪ Doing the wrong thing ♪",
    "♪ And I feel something so wrong ♪",
    "♪ Doing the right thing ♪",
    "♪ I couldn&#39;t lie, couldn&#39;t\nlie, couldn&#39;t lie ♪",
    "♪ Everything that kills\nme makes me feel alive ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars,\nwe&#39;ll be counting stars ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the things we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars ♪",
    "♪ We&#39;ll be, we&#39;ll be counting stars ♪",
    "♪ Yeah, yeah ♪",
    "♪ I feel your love, and I feel it burn ♪",
    "♪ Down this river, every turn ♪",
    "♪ Hope is our four-letter word ♪",
    "♪ Make that money, watch it burn ♪",
    "♪ Old, but I&#39;m not that old ♪",
    "♪ Young, but I&#39;m not that bold ♪",
    "♪ And I don&#39;t think the world is sold ♪",
    "♪ On just doing what we&#39;re told ♪",
    "♪ And I feel something so wrong ♪",
    "♪ Doing the right thing ♪",
    "♪ I couldn&#39;t lie, couldn&#39;t\nlie, couldn&#39;t lie ♪",
    "♪ Everything that drowns\nme makes me wanna fly ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars,\nwe&#39;ll be counting stars ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars ♪",
    "♪ We&#39;ll be, we&#39;ll be counting stars ♪",
    "♪ Oh, take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Everything that kills me ♪",
    "♪ Makes me feel alive ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars,\nwe&#39;ll be counting stars ♪",
    "♪ Lately, I&#39;ve been,\nI&#39;ve been losing sleep ♪",
    "♪ Dreaming about the\nthings that we could be ♪",
    "♪ But baby, I&#39;ve been,\nI&#39;ve been praying hard ♪",
    "♪ Said no more counting dollars ♪",
    "♪ We&#39;ll be, we&#39;ll be counting stars ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "♪ Take that money, watch it burn ♪",
    "♪ Sink in the river the\nlessons I&#39;ve learned ♪",
    "(ceiling rumbling)",
    "(man loudly crashing)",
    "(light buzzing)",
    "(footsteps lightly rustling)"
];

subtitles_3.forEach(text => {
    console.log(parseSubtitle(text));
});
